export const ACTIVE_ALERT_PARAMS = Object.freeze({
  area: "",
  certainty: "",
  code: "",
  event: "",
  limit: "",
  message_type: "",
  point: "",
  region: "",
  region_type: "",
  severity: "",
  status: "",
  urgency: "",
  zone: "",
});
